__default__: 
  call: "qsub -cwd"
  nodes: ""
  mem_per_cpu: "-l h_vmem="
  partition: ""
  runtime: "-l h_rt="
  threads: "-pe smp "

mg_filtering:
  partition: "-l highmem"

mt_filtering:
  partition: "-l highmem"

bwa_index:
  partition: "-l highmem"

mapping_on_assembly:
  partition: "-l highmem"

index_bam:
  partition: "-l highmem"

megahit_assembly_from_preprocessing:
  partition: "-l highmem"

megahit_assembly_from_unmapped:
  partition: "-l highmem"

metaspades_assembly_from_preprocessing:
  partition: "-l highmem"

metaspades_assembly_from_unmapped:
  partition: "-l highmem"

cap3:
  partition: "-l highmem"

extract_unmapped_from_megahit:
  partition: "-l highmem"

extract_unmapped_from_hybrid_assembly:
  partition: "-l highmem"

megahit_hybrid_assembly_1:
  partition: "-l highmem"

megahit_hybrid_assembly_2:
  partition: "-l highmem"

metaspades_hybrid_assembly_1:
  partition: "-l highmem"

metaspades_hybrid_assembly_2:
  partition: "-l highmem"

collapse_hybrid_assemblies:
  partition: "-l highmem"

extract_unmapped:
  partition: "-l highmem"

call_contig_depth:
  partition: "-l highmem"

call_gene_depth:
  partition: "-l highmem"

DAS_tool:
  partition: "-l highmem"

prepare_gridReads:
  partition: "-l highmem"

grid:
  partition: "-l highmem"

vizbin:
  partition: "-l highmem"

vizbin_mt:
  partition: "-l highmem"

binny:
  partition: "-l highmem"

kraken_contigs:
  partition: "-l highmem"

kraken_reads:
  partition: "-l highmem"

GTDBtk_bins_single:
  partition: "-l highmem"

dRep_simple:
  partition: "-l highmem"

call_contig_depth:
  partition: "-l highmem"
