__default__: 
  nodes: ""
  partition: "-p batch"
  qos: "--qos normal"
  call: "sbatch"
  mem_per_cpu: "--mem-per-cpu "  
  runtime: "-t "
  threads: "-n "

prepare_input_data_copy:
  nodes: "-N 1"

mg_filtering:
  nodes: "-N 1"

mt_filtering:
  nodes: "-N 1"

trimming:
  nodes: "-N 1"

bwa_index:
  partition: "-p bigmem"

mapping_on_assembly:
  nodes: "-N 1"
  partition: "-p bigmem"

index_bam:
  nodes: "-N 1"
  partition: "-p bigmem"

megahit_assembly_from_preprocessing:
  partition: "-p bigmem"
  qos: "--qos long"

megahit_assembly_from_unmapped:
  partition: "-p bigmem"
  qos: "--qos long"

metaspades_assembly_from_preprocessing:
  partition: "-p bigmem"
  qos: "--qos long"

metaspades_assembly_from_unmapped:
  partition: "-p bigmem"
  qos: "--qos long"

merge_assembly_cap3:
  partition: "-p bigmem"
  qos: "--qos long"

merge_hybrid_assembly_cap3:
  partition: "-p bigmem"
  qos: "--qos long"

extract_unmapped_from_megahit:
  nodes: "-N 1"
  partition: "-p bigmem"

extract_unmapped_from_hybrid_assembly:
  nodes: "-N 1"
  partition: "-p bigmem"

megahit_hybrid_assembly_1:
  partition: "-p bigmem"
  qos: "--qos long"

megahit_hybrid_assembly_2:
  partition: "-p bigmem"
  qos: "--qos long"

metaspades_hybrid_assembly_1:
  partition: "-p bigmem"
  qos: "--qos long"

metaspades_hybrid_assembly_2:
  partition: "-p bigmem"
  qos: "--qos long"

collapse_hybrid_assemblies:
  partition: "-p bigmem"
  qos: "--qos normal"

extract_unmapped:
  nodes: "-N 1"
  partition: "--qos bigmem"

DAS_tool:
  partition: "-p bigmem"

prepare_gridReads:
  partition: "-p bigmem"

grid:
  partition: "-p bigmem"

vizbin:
  partition: "-p bigmem"

vizbin_mt:
  partition: "-p bigmem"

kraken_contigs:
  nodes: "-N 1"
  partition: "-p bigmem"

kraken_reads:
  nodes: "-N 1"
  partition: "-p bigmem"

GTDBtk_bins_single:
  nodes: "-N 1"
  partition: "-p bigmem"
