__default__: 
  nodes: ""
  partition: ""
  call: "sbatch  --nodelist="
  mem_per_cpu: "--mem-per-cpu "  
  runtime: "-t "
  threads: "-c "
  stdout: "-o mump.{rule}.{wildcards}.stdout"
  tmpdir: "-tmpdir=/scratch"

bwa_index:
  stdout: "-o IMP3.{rule}.stdout"
  nodes: "-N 1"

index_bam:
  stdout: "-o IMP3.{rule}.stdout"

prepare_input_data_copy:
  nodes: "-N 1"

mg_filtering:
  nodes: "-N 1"

mt_filtering:
  nodes: "-N 1"

trimming:
  nodes: "-N 1"

mapping_on_assembly:
  nodes: "-N 1"

extract_unmapped_from_megahit:
  nodes: "-N 1"

extract_unmapped_from_hybrid_assembly:
  nodes: "-N 1"

extract_unmapped:
  nodes: "-N 1"

kraken_contigs:
  nodes: "-N 1"

kraken_reads:
  nodes: "-N 1"

GTDBtk_bins_single:
  nodes: "-N 1"
